apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app.kubernetes.io/name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-app
    spec:
      containers:
        - name: node
          image: docker.pkg.github.com/codytrey/codytrey.github.io/node-app:v0.1.0
          ports:
          - containerPort: 3000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: node-api-secret
                  key: API_KEY