apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app.kubernetes.io/name: node-app
spec:
  containers:
    - name: node
      image: docker.pkg.github.com/codytrey/codytrey.github.io/node-app:v0.1.0
      ports:
      - containerPort: 3000
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: node-api-secret
              key: API_KEY