apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app.kubernetes.io/name: node-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: node-app